CREATE PROCEDURE [dbo].[spRegistrationInsert]
	@stateVoterID NVARCHAR(50),
	@fname NVARCHAR(50),
	@mname NVARCHAR(50),
	@lname NVARCHAR(50),
	@nameSuffix NVARCHAR(50),
	@birthDate DATETIME2(7),
	@gender NVARCHAR(1),
	@regStNum NVARCHAR(50),
	@regStFrac NVARCHAR(50),
	@regStName NVARCHAR(50),
	@regStType NVARCHAR(50),
	@regUnitType NVARCHAR(50),
	@regStPreDir NVARCHAR(50),
	@regStPostDir NVARCHAR(50),
	@regStUnitNum NVARCHAR(50),
	@regCity NVARCHAR(50),
	@regState NVARCHAR(50),
	@regZipCode NVARCHAR(50),
	@countyCode NVARCHAR(50),
	@precinctCode NVARCHAR(50),
	@precinctPart NVARCHAR(50),
	@legislativeDistrict NVARCHAR(50),
	@congressionalDistrict NVARCHAR(50),
	@mail1 NVARCHAR(50),
	@mail2 NVARCHAR(50),
	@mail3 NVARCHAR(50),
	@mail4 NVARCHAR(50),
	@mailCity NVARCHAR(50),
	@mailZip NVARCHAR(50),
	@mailState NVARCHAR(50),
	@mailCountry NVARCHAR(50),
	@registrationDate DATETIME2(7),
	@absenteeType NVARCHAR(50),
	@lastVoted DATETIME2(7),
	@statusCode NVARCHAR(50)
AS
	INSERT INTO Registration(
		StateVoterId,
		FName,
		MName,
		LName,
		NameSuffix,
		BirthDate,
		BirthYear,
		Gender,
		RegStNum,
		RegStFrac,
		RegStName,
		RegStType,
		RegUnitType,
		RegStPreDirection,
		RegStPostDirection,
		RegStUnitNum,
		RegCity,
		RegState,
		RegZipCode,
		CountyCode,
		PrecinctCode,
		PrecinctPart,
		LegislativeDistrict,
		CongressionalDistrict,
		Mail1,
		Mail2,
		Mail3,
		Mail4,
		MailCity,
		MailZip,
		MailState,
		MailCountry,
		RegistrationDate,
		AbsenteeType,
		LastVoted,
		StatusCode
	)
	VALUES(
		@stateVoterID,
		@fname,
		@mname,
		@lname,
		@nameSuffix,
		@birthDate,
		YEAR(@birthDate),
		@gender,
		@regStNum,
		@regStFrac,
		@regStName,
		@regStType,
		@regUnitType,
		@regStPreDir,
		@regStPostDir,
		@regStUnitNum,
		@regCity,
		@regState,
		@regZipCode,
		@countyCode,
		@precinctCode,
		@precinctPart,
		@legislativeDistrict,
		@congressionalDistrict,
		@mail1,
		@mail2,
		@mail3,
		@mail4,
		@mailCity,
		@mailZip,
		@mailState,
		@mailCountry,
		@registrationDate,
		@absenteeType,
		@lastVoted,
		@statusCode
	)

RETURN 0
